# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        # the name of the "filter set"
        image_album:

            # adjust the image quality to 80%
            quality: 80

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 200x150 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 200, 150 ], mode: outbound }
